# Generated by Django 3.2.6 on 2021-08-11 17:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_desc', models.TextField(blank=True, max_length=500)),
                ('long_desc', models.CharField(blank=True, max_length=30)),
                ('image', models.ImageField(blank=True, upload_to='image')),
                ('degree', models.CharField(blank=True, max_length=30)),
                ('year_of_passing', models.CharField(blank=True, max_length=30)),
                ('certificate', models.ImageField(blank=True, upload_to='certificate')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
