# Generated by Django 3.2.6 on 2021-08-12 03:34

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='long_desc',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
