# Generated by Django 3.2.6 on 2021-08-12 03:44

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_profile_long_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='long_desc',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
    ]
